### ISSUE TITLE
set up daily task to update notebook

### ISSUE THREAD

**Issue by cascandaliato** [cascandaliato/covid19-notebook#1]
### auto push
https://github.com/casca/casca.dev/blob/master/.github/workflows/lighthouse-audit.yml

### container
```yaml
jobs:
  testbox:
    runs-on: ubuntu-latest
    container:
      image: azul/zulu-openjdk-alpine:8-jre
    steps:  
    - uses: actions/checkout@v2
    - name: What OS is running
      run: uname -a
    - name: What java version do we have
      run: java -version
```
