### ISSUE TITLE
build docker image for papermill

### ISSUE THREAD

**Issue by cascandaliato** [cascandaliato/covid19-notebook#2]
### bash
```bash
apt-get install python3 python3-pip
python3 -m pip install notebook papermill
python3 -m pip install -r requirements.txt
papermill charts.ipynb output.ipynb
```

### GitHub Action to build images
```yaml
‐ name: build-push
  uses: docker/build-push-action@v1
  with:
    username: ${{ DOCKER_USERNAME }}
    password: ${{ DOCKER_PASSWORD }}
    registry: myregistry
    repository: myorg/myrepo
    tags: v1
```

### dockerfile

https://phoenixnap.com/kb/docker-cmd-vs-entrypoint
https://github.com/marketplace/actions/build-and-push-docker-images#labels
https://docs.github.com/en/actions/language-and-framework-guides/publishing-docker-images

### apt clean-up

```dockerfile
RUN apt-get update && apt-get install -y \
    curl \
    git \
    libsqlite3-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*
```
